name: CD - Deploy to GKE (PROD)

on:
  push:
    branches:
      - prod

env:
  PROJECT_ID: proyecto-golgana-cloud
  GKE_CLUSTER: golgana-cluster
  GKE_REGION: us-central1
  IMAGE_BACKEND: gabimac033/golgana-backend
  IMAGE_FRONTEND: gabimac033/golgana-frontend

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION

      - name: Deploy to GKE
        run: |
          kubectl apply -f appdemo/k8s-manifests/ --recursive
