name: CI - Build and Push Images (DEV)

on:
  pull_request:
    branches:
      - dev

env:
  IMAGE_BACKEND: gabimac033/golgana-backend
  IMAGE_FRONTEND: gabimac033/golgana-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          docker build -t $IMAGE_BACKEND:dev ./appdemo/backend
          docker push $IMAGE_BACKEND:dev

      - name: Build and Push Frontend
        run: |
          docker build -t $IMAGE_FRONTEND:dev ./appdemo/frontend
          docker push $IMAGE_FRONTEND:dev